/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVeArtProxy,
  IVeArtProxyInterface,
} from "../../../contracts/interfaces/IVeArtProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "generateConfig",
    outputs: [
      {
        components: [
          {
            internalType: "int256",
            name: "_tokenId",
            type: "int256",
          },
          {
            internalType: "int256",
            name: "_balanceOf",
            type: "int256",
          },
          {
            internalType: "int256",
            name: "_lockedEnd",
            type: "int256",
          },
          {
            internalType: "int256",
            name: "_lockedAmount",
            type: "int256",
          },
        ],
        internalType: "struct IVeArtProxy.Config",
        name: "cfg",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "output",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVeArtProxy__factory {
  static readonly abi = _abi;
  static createInterface(): IVeArtProxyInterface {
    return new Interface(_abi) as IVeArtProxyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVeArtProxy {
    return new Contract(address, _abi, runner) as unknown as IVeArtProxy;
  }
}
