/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGaugeFactory,
  IGaugeFactoryInterface,
} from "../../../../contracts/interfaces/factories/IGaugeFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_forwarder",
        type: "address",
      },
      {
        internalType: "address",
        name: "_pool",
        type: "address",
      },
    ],
    name: "createGauge",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGaugeFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IGaugeFactoryInterface {
    return new Interface(_abi) as IGaugeFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGaugeFactory {
    return new Contract(address, _abi, runner) as unknown as IGaugeFactory;
  }
}
